language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - build-tools-20.0.0
    - android-20
  licenses:
    - android-sdk-license-5be876d5

script: ./gradlew build

branches:
  except:
    - gh-pages

notifications:
  email: false
